[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "climate-data-analysis-python"
version = "0.1.0"
description = "Open-source Python tools for climate and oceanographic data analysis and scientific visualization."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
    { name = "Fabio Vieira Machado" }
]
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "matplotlib",
    "xarray",
    "statsmodels"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
[tool.black]
target-version = ["py310"]
line-length = 88
